[mypy]
python_version = 3.11
# Ігноруємо попередження про відсутність вбудованої типізації у Django та DRF
ignore_missing_imports = True
check_untyped_defs = True

# Повністю виключаємо з аналізу автоматично згенеровані файли
exclude = (migrations|apps\.py|settings\.py|manage\.py|wsgi\.py|asgi\.py)